name: Build board-2.bin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone qca-swiss-army-knife
        run: git clone https://github.com/qca/qca-swiss-army-knife.git

      - name: Build board-2.bin
        run: |
          cp ${{ github.workspace }}/bdwlan.bin ${{ github.workspace }}/qca-swiss-army-knife/tools/scripts/ath11k/
          cd qca-swiss-army-knife/tools/scripts/ath11k
          python3 ath11k-bdencoder -c ${{ github.workspace }}/board-2.json -o ${{ github.workspace }}/board-2.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: board-2.bin
          path: board-2.bin
